-- MySQL Script generated by MySQL Workbench
-- Mon May 23 18:06:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `account_id` INT ZEROFILL NOT NULL,
  `account_type_id` INT NOT NULL,
  `account_number` INT(16) NOT NULL,
  `asociated_card` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `account_number_UNIQUE` (`account_number` ASC) VISIBLE,
  INDEX `fk_account_account_type1_idx` (`account_type_id` ASC) VISIBLE,
  UNIQUE INDEX `account_type_id_UNIQUE` (`account_type_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_account_cards1_idx` (`asociated_card` ASC) VISIBLE,
  UNIQUE INDEX `asociated_card_UNIQUE` (`asociated_card` ASC) VISIBLE,
  CONSTRAINT `fk_account_account_type1`
    FOREIGN KEY (`account_type_id`)
    REFERENCES `mydb`.`account_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_cards1`
    FOREIGN KEY (`asociated_card`)
    REFERENCES `mydb`.`card` (`card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account_type` (
  `type_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `type_id_UNIQUE` (`type_id` ASC) VISIBLE,
  UNIQUE INDEX `type_name_UNIQUE` (`type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `country_id` INT ZEROFILL NOT NULL,
  `street_name` VARCHAR(50) NOT NULL,
  `flat_number` VARCHAR(15) NULL,
  `building_number` VARCHAR(15) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `city` VARCHAR(40) NOT NULL,
  `state` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_Address_country1_idx` (`country_id` ASC) VISIBLE,
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Address_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card` (
  `card_id` INT ZEROFILL NULL AUTO_INCREMENT,
  `card_type_id` INT NOT NULL,
  `pan` CHAR(16) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `cvv` CHAR(3) NOT NULL,
  PRIMARY KEY (`card_id`),
  INDEX `fk_cards_card_type1_idx` (`card_type_id` ASC) VISIBLE,
  UNIQUE INDEX `card_id_UNIQUE` (`card_id` ASC) VISIBLE,
  UNIQUE INDEX `pan_UNIQUE` (`pan` ASC) VISIBLE,
  CONSTRAINT `fk_cards_card_type1`
    FOREIGN KEY (`card_type_id`)
    REFERENCES `mydb`.`card_type` (`card_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card_type` (
  `card_type_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `card_type_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`card_type_id`),
  UNIQUE INDEX `card_type_id_UNIQUE` (`card_type_id` ASC) VISIBLE,
  UNIQUE INDEX `card_type_name_UNIQUE` (`card_type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `cart_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `item` VARCHAR(50) NOT NULL,
  `price` DECIMAL(6,3) NOT NULL,
  `purchase_id` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `cart_id_UNIQUE` (`cart_id` ASC) VISIBLE,
  UNIQUE INDEX `item_UNIQUE` (`item` ASC) VISIBLE,
  INDEX `fk_cart_purchase1_idx` (`purchase_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_purchase1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `mydb`.`purchase` (`purchase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(50) NOT NULL,
  `country_code` VARCHAR(5) NOT NULL,
  `countrycol` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `country_name_UNIQUE` (`country_name` ASC) VISIBLE,
  UNIQUE INDEX `country_code_UNIQUE` (`country_code` ASC) VISIBLE,
  UNIQUE INDEX `country_id_UNIQUE` (`country_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`currency` (
  `currency_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(15) NOT NULL,
  `currency_symbol` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`currency_id`),
  UNIQUE INDEX `currency_id_UNIQUE` (`currency_id` ASC) VISIBLE,
  UNIQUE INDEX `currency_name_UNIQUE` (`currency_name` ASC) VISIBLE,
  UNIQUE INDEX `currency_symbol_UNIQUE` (`currency_symbol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `document_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `file_type_id` INT NOT NULL,
  `document_file` LONGBLOB NOT NULL,
  `file_name` VARCHAR(50) NOT NULL,
  `uploaded_date` DATETIME NOT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `fk_document_file_trpe1_idx` (`file_type_id` ASC) VISIBLE,
  UNIQUE INDEX `document_id_UNIQUE` (`document_id` ASC) VISIBLE,
  CONSTRAINT `fk_document_file_trpe1`
    FOREIGN KEY (`file_type_id`)
    REFERENCES `mydb`.`file_type` (`file_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fee` (
  `fee_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `fee_type` VARCHAR(15) NOT NULL,
  `percentage` DECIMAL(1,3) NOT NULL,
  PRIMARY KEY (`fee_id`),
  UNIQUE INDEX `fee_id_UNIQUE` (`fee_id` ASC) VISIBLE,
  UNIQUE INDEX `fee_type_UNIQUE` (`fee_type` ASC) VISIBLE,
  UNIQUE INDEX `percentage_UNIQUE` (`percentage` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`file_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`file_type` (
  `file_type_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `file_type_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`file_type_id`),
  UNIQUE INDEX `file_type_id_UNIQUE` (`file_type_id` ASC) VISIBLE,
  UNIQUE INDEX `file_type_name_UNIQUE` (`file_type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gender` (
  `gender_id` INT NOT NULL AUTO_INCREMENT,
  `gender_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`gender_id`),
  UNIQUE INDEX `gender_id_UNIQUE` (`gender_id` ASC) VISIBLE,
  UNIQUE INDEX `gender_name_UNIQUE` (`gender_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(15) NULL,
  `last_name` VARCHAR(20) NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(55) NULL,
  `phone_number` VARCHAR(15) NULL,
  `gender` VARCHAR(25) NULL,
  `street_name` VARCHAR(50) NULL,
  `flat_number` VARCHAR(15) NULL,
  `building_number` VARCHAR(15) NULL,
  `zip_code` VARCHAR(10) NULL,
  `city` VARCHAR(40) NULL,
  `state` VARCHAR(30) NULL,
  `document` LONGBLOB NULL,
  `balance` DECIMAL NULL,
  `username` VARCHAR(25) NULL,
  `password` VARCHAR(50) NULL,
  `account_number` INT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `person_id` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(15) NULL,
  `last_name` VARCHAR(20) NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(55) NULL,
  `phone_number` VARCHAR(15) NULL,
  `gender` VARCHAR(25) NULL,
  `street_name` VARCHAR(50) NULL,
  `flat_number` VARCHAR(15) NULL,
  `building_number` VARCHAR(15) NULL,
  `zip_code` VARCHAR(10) NULL,
  `city` VARCHAR(40) NULL,
  `state` VARCHAR(30) NULL,
  `document` LONGBLOB NULL,
  `balance` DECIMAL NULL,
  `username` VARCHAR(25) NULL,
  `password` VARCHAR(50) NULL,
  `account_number` INT NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase` (
  `purchase_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `purchaser` INT ZEROFILL NOT NULL,
  `service_id` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`purchase_id`),
  INDEX `fk_purchase_history_user1_idx` (`purchaser` ASC) VISIBLE,
  INDEX `fk_purchase_history_Serices1_idx` (`service_id` ASC) VISIBLE,
  UNIQUE INDEX `purchase_id_UNIQUE` (`purchase_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_history_user1`
    FOREIGN KEY (`purchaser`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_history_Serices1`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`service` (`service_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `service_id` INT NOT NULL,
  `service_item` VARCHAR(20) NULL,
  `service_provider` VARCHAR(25) NULL,
  `service_provider_account` INT NULL,
  `service_provider_document` LONGBLOB NULL,
  `service_price` DECIMAL NULL,
  `status` VARCHAR(15) NULL,
  `steet_name` VARCHAR(50) NULL,
  `flat_number` VARCHAR(15) NULL,
  `building_number` VARCHAR(15) NULL,
  `zip_code` VARCHAR(10) NULL,
  `city` VARCHAR(40) NULL,
  `state` VARCHAR(30) NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `service_id` INT NOT NULL,
  `service_item` VARCHAR(20) NULL,
  `service_provider` VARCHAR(25) NULL,
  `service_provider_account` INT NULL,
  `service_provider_document` LONGBLOB NULL,
  `service_price` DECIMAL NULL,
  `status` VARCHAR(15) NULL,
  `steet_name` VARCHAR(50) NULL,
  `flat_number` VARCHAR(15) NULL,
  `building_number` VARCHAR(15) NULL,
  `zip_code` VARCHAR(10) NULL,
  `city` VARCHAR(40) NULL,
  `state` VARCHAR(30) NULL,
  PRIMARY KEY (`service_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`service_provider` (
  `provider_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(30) NOT NULL,
  `tax_number` VARCHAR(50) NOT NULL,
  `registratoin_number` VARCHAR(30) NOT NULL,
  `account_id` INT(10) ZEROFILL NOT NULL,
  `document_id` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`provider_id`),
  UNIQUE INDEX `provider_id_UNIQUE` (`provider_id` ASC) VISIBLE,
  UNIQUE INDEX `provider_name_UNIQUE` (`provider_name` ASC) VISIBLE,
  INDEX `fk_service_provider_account1_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `fk_service_provider_document1_idx` (`document_id` ASC) VISIBLE,
  UNIQUE INDEX `document_id_UNIQUE` (`document_id` ASC) VISIBLE,
  UNIQUE INDEX `tax_number_UNIQUE` (`tax_number` ASC) VISIBLE,
  UNIQUE INDEX `registratoin_number_UNIQUE` (`registratoin_number` ASC) VISIBLE,
  CONSTRAINT `fk_service_provider_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_provider_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `mydb`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `status_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`status_id`),
  UNIQUE INDEX `status_id_UNIQUE` (`status_id` ASC) VISIBLE,
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table` (
  `table_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `table_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`table_id`),
  UNIQUE INDEX `table_id_UNIQUE` (`table_id` ASC) VISIBLE,
  UNIQUE INDEX `table_name_UNIQUE` (`table_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tracker` (
  `ledger_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `table_id` INT NOT NULL,
  `updated_by` INT ZEROFILL NULL,
  `row` INT NOT NULL,
  `column` VARCHAR(25) NOT NULL,
  `previous_value` VARCHAR(100) NOT NULL,
  `updated_time` TIME NOT NULL,
  `updated_date` DATE NOT NULL,
  `trackercol` VARCHAR(45) NULL,
  PRIMARY KEY (`ledger_id`),
  UNIQUE INDEX `ledger_id_UNIQUE` (`ledger_id` ASC) VISIBLE,
  INDEX `fk_ledger_tables1_idx` (`table_id` ASC) VISIBLE,
  INDEX `fk_ledger_user1_idx` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `fk_ledger_tables1`
    FOREIGN KEY (`table_id`)
    REFERENCES `mydb`.`table` (`table_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ledger_user1`
    FOREIGN KEY (`updated_by`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `transaction_id` INT NOT NULL,
  `amount` DECIMAL NULL,
  `transaction_date` DATETIME NULL,
  `user_id` VARCHAR(45) NULL,
  `fee` VARCHAR(45) NULL,
  `transaction_type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction` (
  `transaction_id` INT NOT NULL,
  `amount` DECIMAL NULL,
  `transaction_date` DATETIME NULL,
  `user_id` VARCHAR(45) NULL,
  `fee` VARCHAR(45) NULL,
  `transaction_type` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `currency` VARCHAR(45) NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaction_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaction_type` (
  `transaction_type_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `transaction_type_name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`transaction_type_id`),
  UNIQUE INDEX `transaction_type_id_UNIQUE` (`transaction_type_id` ASC) VISIBLE,
  UNIQUE INDEX `transaction_type_name_UNIQUE` (`transaction_type_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `person_id` INT ZEROFILL NOT NULL,
  `account_id` INT NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `remaining_balance` DECIMAL(12,3) NOT NULL,
  `available_balance` DECIMAL(12,3) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_account1_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_Person1_idx` (`person_id` ASC) VISIBLE,
  UNIQUE INDEX `person_id_UNIQUE` (`person_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_Person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
